"""empty message

Revision ID: 047ef4518315
Revises: 338af4844a51
Create Date: 2025-12-10 17:36:27.396827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047ef4518315'
down_revision = '338af4844a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('user_video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_video_id'], ['user_video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_video')
    # ### end Alembic commands ###
