"""empty message

Revision ID: 338af4844a51
Revises: d89e9bb804e7
Create Date: 2025-12-10 12:49:29.881171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338af4844a51'
down_revision = 'd89e9bb804e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_video', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
