"""empty message

Revision ID: 6e63573b9349
Revises: a43fe9efa189
Create Date: 2025-12-12 14:57:42.345774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e63573b9349'
down_revision = 'a43fe9efa189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('user_image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_image')
    # ### end Alembic commands ###
